var dragonHP = 100;
var dragonNUM = 103;
var dragonType = "not to be reckoned with";
var dragomBestMove = "Fire Smack";
var dragonLastEvo = True;
var dragonAttack = 75;
var dragonDefense = 80;
var dragonSpeed = 200;
var dragonSpecialMove = "Sky Slam"
var dragonSpecialDefense = "Retreat"
var potatoeScarHP = 100;
var potatoeScarNUM = 30;
var potatoeScarType = "ground";
var potatoeScarBestMove = "Dig"
var potatoScarLastEvo = "False"
var potatoeScarAttack = 10
var potatoeScarDefense = 21
var potatoeScarSpeed = 50
var potatoeScarSpecialMove = "DiveBomb"
var potatoeScarSpecialDefense = "Run"
